### ISSUE TITLE
DolphinScheduler 

### ISSUE THREAD

**Issue by progromeryan** [dromara/CloudEon#107]
依赖环境变量设置，比如

export HADOOP_HOME=${HADOOP_HOME:-/home/pubserver/hadoop-3.3.5}
export HADOOP_CONF_DIR=${HADOOP_CONF_DIR:-/home/pubserver/hadoop-3.3.5/etc/hadoop}
export SPARK_HOME1=${SPARK_HOME1:-/home/pubserver/spark-3.4.0-bin-hadoop3}
export SPARK_HOME2=${SPARK_HOME2:-/home/pubserver/spark-3.4.0-bin-hadoop3}
export PYTHON_HOME=${PYTHON_HOME:-/usr/bin/python}
export HIVE_HOME=${HIVE_HOME:-/home/pubserver/hive3.1.3}
export FLINK_HOME=${FLINK_HOME:-/home/pubserver/flink-1.17.0}
export DATAX_HOME=${DATAX_HOME:-/home/pubserver/datax}
export SEATUNNEL_HOME=${SEATUNNEL_HOME:-/opt/soft/seatunnel}
export CHUNJUN_HOME=${CHUNJUN_HOME:-/opt/soft/chunjun}

export PATH=$HADOOP_HOME/bin:$SPARK_HOME1/bin:$SPARK_HOME2/bin:$PYTHON_HOME/bin:$JAVA_HOME/bin:$HIVE_HOME/bin:$FLINK_HOME/bin:$DATAX_HOME/bin:$SEATUNNEL_HOME/bin:$CHUNJUN_HOME/bin:$PATH

**Comment by MuziMin0222** [comment]
Hi，我目前也遇到这样的问题，请问您这边是如何处理的@progromeryan
