### ISSUE TITLE
【问题反馈】openeuler22.03操作系统添加节点时遇到问题Algorithm negotiation fail

### ISSUE THREAD

**Issue by stdnt-xiao** [dromara/CloudEon#121]
经过测试发现是加密算法不适配的问题。联系社区已经解决，提供给其他人参考。
参考链接1：
https://blog.csdn.net/qq_21271511/article/details/121784463
参考链接2：
https://forum.openeuler.org/t/topic/2636/2
实际解决方法如下：
`
打开/etc/ssh/sshd_config文件，在HostKeyAlgorithms和PubkeyAcceptedKeyTypes配置项增加ssh-rsa

# cp /etc/ssh/sshd_config /etc/ssh/sshd_config.20230427
# grep -vE '^#|^$' /etc/ssh/sshd_config
# vi /etc/ssh/sshd_config
HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-512
PubkeyAcceptedKeyTypes ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-512
在HostKeyAlgorithms和PubkeyAcceptedKeyTypes配置项增加ssh-rsa
HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-512,ssh-rsa
PubkeyAcceptedKeyTypes ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-512,ssh-rsa

# systemctl restart sshd
# systemctl status sshd
`

**Comment by Pandas886** [comment]
感谢反馈~方便加下vx吗

**Comment by stdnt-xiao** [comment]
> 感谢反馈~方便加下vx吗

大佬，当然可以，发您gmail邮箱了
