### ISSUE TITLE
[Bug] Startup doris service stuck

### ISSUE THREAD

**Issue by mklzl** [dromara/CloudEon#22]
**Describe the bug**
Startup doris  service stuck

**To Reproduce**

**Expected behavior**
start success

**Environment**
 - CloudEon Version: [ 1.0.0]
 - Java Version: [1.8.0_271-b09]
 - OS: [e.g. CentOS 7.9]

**Screenshots**
![image](https://user-images.githubusercontent.com/36362816/233967300-1f30be2f-2589-4d1a-9002-9b518ac6d88f.png)
![image](https://user-images.githubusercontent.com/36362816/233967361-14bd8578-cca1-4dbb-946e-ef477eaaa3e8.png)

**Additional context**

**Comment by mklzl** [comment]
taint node

**Comment by Pandas886** [comment]
> taint node

Submitting a pull request to FAQ.md with a description of your problem and solution would be greatly appreciated by Cloudeon community.

**Comment by shfpflyawei** [comment]
我也约遇到了类似的问题， v.1.2.0版本  经过排查日志发现 doris 版本是1.1.5
默认镜像是需要cpu 支持 AVX2指令集， 我使用的是虚拟机，重新配置虚拟机的指令集后，doris 正常启动了
