### ISSUE TITLE
发生异常，处理异常。。。ssh 执行命令失败：bash: ctr: command not found

### ISSUE THREAD

**Issue by liliang109696** [dromara/CloudEon#74]
使用的是k8s 1.26.4 用[kubeasz](https://github.com/easzlab/kubeasz) 3.5.3版本安装的，没有ctr命令 是否是因为k8s用的是crictl命令来管理的？怎么解决呢？

**Comment by Pandas886** [comment]
已完成用k8s job替代

**Comment by xlostway** [comment]
你好，我是谢晋峰，你的邮件我已经收到，谢谢！
