### ISSUE TITLE
 readiness probe failed.

### ISSUE THREAD

**Issue by lexuan1993** [dromara/CloudEon#79]
**Describe the bug**
Due to the port conflict, I have changed the zookeeper's default config:  zookeeper.client.port to 2281 , It won't start when I deploy the zookeeper service.

**To Reproduce**
Modify the default zookeeper configuration.

**Environment**
 - CloudEon Version: [1.0.0]
 - Java Version: [OpenJDK 1.8]
 - OS: [CentOS 7.9]
 - Kubernetes: [1.27.1]

**Screenshots**
<img width="982" alt="image" src="https://github.com/dromara/CloudEon/assets/25922451/2c60c0b5-f8ac-490c-87ec-2e160d1069a3">
<img width="737" alt="image" src="https://github.com/dromara/CloudEon/assets/25922451/13860869-5b8b-493d-afa7-31bc99fa3d38">
<img width="937" alt="image" src="https://github.com/dromara/CloudEon/assets/25922451/1900d725-7d00-4cb7-8ae5-e2f231e01adf">
<img width="819" alt="image" src="https://github.com/dromara/CloudEon/assets/25922451/46ed6e05-f2a2-47d7-ba7e-cf3dba0fc298">

**Comment by Pandas886** [comment]
Thanks for the feedback, the issue has been resolved in the dev branch
