### ISSUE TITLE
[Feature] 修改Helm部署为Operator模式

### ISSUE THREAD

**Issue by cdmikechen** [dromara/CloudEon#80]
**Is your feature request related to a problem? Please describe.**
Helm 部署为一次性的全局安装，并不会对当前集群的状态做持续性的运维管理。
建议后面将Helm部署逐步迁移为Operator形式，这样可以做到完全云原生的资源全生命周期管理。

**Describe the solution you'd like**
目前可以使用go-client的客户端实现，不过考虑到技术栈的统一性，我个人建议使用 [java-opeartor-sdk](https://github.com/operator-framework/java-operator-sdk)来实现。

**Describe alternatives you've considered**
实际大数据生态中已经有很多组件已将实现了Operator，比如 Spark-Operator, Solr-Operator, Cassandra-Operator, Flink-Operator。

在条件成熟的时候都可以引入作为技术备选。

**Additional context**
NA

**Comment by Pandas886** [comment]
cloudeon最新版没有使用helm部署组件
