### ISSUE TITLE
各种组件现在缺少动态扩容的地方

### ISSUE THREAD

**Issue by progromeryan** [dromara/CloudEon#91]
如果新增机器的，组件貌似缺少动态扩容的地方，一旦固定下来如何扩容了

**Comment by Pandas886** [comment]
comming soon.

**Comment by Pandas886** [comment]
@progromeryan Thank you for the feedback. Are you interested in participating in this project together? You can add me on WeChat and mention your GitHub ID.

**Comment by MuziMin0222** [comment]
Hi，请问这个是如何解决的呢，给组件进行动态扩缩容
