### ISSUE TITLE
[Enhancement] Make Command page's 'Command Name' more clearer

### ISSUE THREAD

**Issue by leeoo** [dromara/CloudEon#95]
**Is your feature request related to a problem? Please describe.**
Env: CloudEon v1.2.0
Command page's 'Command Name' cloumn is not clear to find out which service component after executed many commands.
![a2882f119b2d381feb69b4e49d7eef5](https://github.com/dromara/CloudEon/assets/2136182/823c981b-85b7-40fe-abe5-534579fb5da5)

**Describe the solution you'd like**
Add service component name(s) to 'Command Name' column, or maybe we can add new column to display service component name(s).

**Describe alternatives you've considered**

**Additional context**

**Comment by Pandas886** [comment]
finished in dev.
