### ISSUE TITLE
[Enhancement] Remove HDFS/YARN dependency requirements for Dinky/Trino/DolphinScheduler/Flink

### ISSUE THREAD

**Issue by leeoo** [dromara/CloudEon#97]
**Is your feature request related to a problem? Please describe.**
In my bigdata environment, there is no any Hadoop components, I use MinIO as the DFS, and use ZooKeeper for Flink HA,
when I deploy Dinky/Trino/DolphinScheduler/Flink on CloudEon, it blocks me, and popup tips "需要提前安装服务：HDFS, YARN".

Actually, HDFS/YARN is NOT the only option for Dinky/Trino/DolphinScheduler/Flink components, for example, we can use Amazon S3, MinIO, Alibaba OSS to replace HDFS, and using ZooKeeper to replace YARN for Flink standalone HA, so these two components shoud NOT be the required option.

**Describe the solution you'd like**
Remove HDFS/YARN dependency requirements for Dinky/Trino/DolphinScheduler/Flink.

**Describe alternatives you've considered**

**Additional context**

**Comment by Pandas886** [comment]
I think it is better to make a new stack(eg:  KDP-xx  ) to support  this issue.
